name: Build and Test KMP Project

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build project (Android, Desktop, iOS)
        run: ./gradlew build --max-workers=$(sysctl -n hw.ncpu)

      - name: Run all tests
        run: ./gradlew check --max-workers=$(sysctl -n hw.ncpu)

  android:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug --max-workers=$(sysctl -n hw.ncpu)

      - name: Run Android Unit Tests
        run: ./gradlew testDebugUnitTest --max-workers=$(sysctl -n hw.ncpu)

  ios:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Install Xcode dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch

      - name: Build iOS Framework
        run: ./gradlew linkReleaseFrameworkIosX64 --max-workers=$(sysctl -n hw.ncpu)

      - name: Run iOS Tests
        run: ./gradlew iosX64Test --max-workers=$(sysctl -n hw.ncpu)

  desktop:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Desktop App
        run: ./gradlew packageDistributionForCurrentOS --max-workers=$(sysctl -n hw.ncpu)

      - name: Run Desktop Unit Tests
        run: ./gradlew test --max-workers=$(sysctl -n hw.ncpu)
